AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates a simple API Gateway with HTTP proxy integration

Resources:
  HttpProxyApi:
    Type: AWS::Serverless::Api # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html
    Properties:
      Name: HTTPProxyAPI
      StageName: test
      EndpointConfiguration: REGIONAL
      DefinitionBody:
        swagger: '2.0'
        info:
          title: HTTPProxyAPI
          description: A simple API with HTTP proxy integration
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              parameters:
                - name: proxy
                  in: path
                  required: true
                  type: string
              x-amazon-apigateway-integration:
                type: http_proxy
                uri: http://petstore-demo-endpoint.execute-api.com/{proxy}
                httpMethod: ANY
                passthroughBehavior: when_no_match
                requestParameters:
                  integration.request.path.proxy: method.request.path.proxy
                
Outputs:
  ApiUrl:
    Description: "The URL of the HTTP Proxy API Gateway"
    Value: !Sub "https://${HttpProxyApi}.execute-api.${AWS::Region}.amazonaws.com/test/{proxy}"